### ISSUE TITLE
Improve Swarm scheduler to take more metrics and parameters into account

### ISSUE THREAD

**Issue by abronan** [docker/swarm#1703]
This is an umbrella issue as I just realized there are many issues regarding the scheduler and how to improve it and add more awareness of the nodes and their characteristics. The list below:
- [ ] #1702 Scheduler should be aware of exclusive resource assignments (eg. cpusets)
- [ ] #1678 Enhance the scheduler with knowledge about Disk space and inode usage.
- [ ] #1693 Adding network bandwidth knowledge to the schedulers

Feel free to edit and add more.

/cc @vieux @dongluochen @chanwit @nishanttotla

**Comment by abronan** [comment]
(Tentatively added a milestone to it, feel free to change that)

**Comment by chanwit** [comment]
Thank you @abronan 
For me, a node's network utilization is the first priority since a cluster we have deployed is network IO intensive rather than CPU and memory.

Basically, I'll be working on a PR for #1693 using rx/tx without waiting for bandwidth control to happen in the Engine.

Is there any suggestion of how should I proceed this.
  * Should it be a new strategy?
  * Or should it extend the original `spread` and `binpack`?

**Comment by nishanttotla** [comment]
There are a few other issues under the `area/scheduler` label. I would suggest that we pick a milestone (like 1.2.0 here) and use this issue to prioritize which ones we want to have by that. In particular #383, #601 and #1396 are the ones not listed above.

**Comment by abronan** [comment]
@nishanttotla I thought about adding those after doing some research but I think that they are not directly related. Here it's more about improving the scheduler to take smarter decisions based on more parameters.
